### ISSUE TITLE
issue on composer update 

### ISSUE THREAD

**Issue by jacksoncool** [madebyraygun/trending-posts#1]
I keep getting the following issue on composer update: 

Your requirements could not be resolved to an installable set of packages.
                                                                                                                                                   
  Problem 1                                                                                                                                        
    - The requested package madebyraygun/trending-posts could not be found in any version, there may be a typo in the package name. 

any idea?

**Comment by daltonrooney** [comment]
Most likely that means the path to the folder in your composer.json is incorrect. It can be a relative path from the folder where composer.json is located or an absolute path in the filesystem. Double-check the path and let me know. 

If you’re still having problems I can put the repo on packagist, I still want to polish it up for general release in the plugin store but it should be fine to use as-is.

**Comment by jacksoncool** [comment]
yes, still issues. same message. any help would be appreciated.

**Comment by daltonrooney** [comment]
Just published to packagist and updated installation instructions. Try `composer require madebyraygun/trending-posts` from the app directory and see if that works.

I'm also going to publish to the Craft Plugin Store so that should make it even easier.
