### ISSUE TITLE
Track days infinate

### ISSUE THREAD

**Issue by deanfields** [madebyraygun/trending-posts#7]
Is there a way to make track days infinite? Or does it have to be set to something?

**Comment by daltonrooney** [comment]
Hmmm, I don't think the database structure is really optimized for that, it would definitely give performance problems over time.

If you think about it, a rolling count and a total incremental count are two different things. It's easy to create a single entry for each ID and just increment every time a page is visited. That's what I would do if I wanted to track infinite days.

For rolling count, we have to keep a tally for the last (x) days, which means we need to keep summary data for each day. And every day we have to run a cleanup on out-of-date summaries. 

This plugin was really meant for a list of popular posts _this week_ or _this month_, for an all time count I would try https://plugins.craftcms.com/view-count
